AuroraBricksIntex/Components/ColorTypesViewComponent.cs
using AuroraBricksIntex.Models;
using Microsoft.AspNetCore.Mvc;

namespace AuroraBricksIntex.Components
{
    public class ColorTypesViewComponent : ViewComponent
    {
        private ILegoRepository _repo;
        //constructor
        public ColorTypesViewComponent(ILegoRepository temp)
        {
            _repo = temp;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedColorType = RouteData?.Values["colorType"];
            var colorTypes = _repo.Products
               .Select(x => x.PrimaryColor)
               .Distinct()
               .OrderBy(x => x);

            return View(colorTypes);
        }

    }
}

AuroraBricksIntex/Components/ProductCategoryTypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using AuroraBricksIntex.Models;
using Microsoft.Build.Framework;

namespace AuroraBricksIntex.Components
{
    public class ProductCategoryTypesViewComponent : ViewComponent
    {
        private ILegoRepository _repo;
        //constructor
        public ProductCategoryTypesViewComponent(ILegoRepository temp)
        {
            _repo = temp;
        }
            public IViewComponentResult Invoke()
        {
            ViewBag.SelectedProductType = RouteData?.Values["productCategoryType"];
            var productCategoryTypes = _repo.Products
               .Select(x => x.Category)
               .Distinct()
               .OrderBy(x => x);

            return View(productCategoryTypes);
        }
    }

}

AuroraBricksIntex/Controllers/HomeController.cs
using AuroraBricksIntex.Models;
using Microsoft.AspNetCore.Mvc;
using NuGet.ProjectModel;
using System.Diagnostics;
using AuroraBricksIntex.Models.ViewModels;
using System.Drawing.Printing;
using Microsoft.EntityFrameworkCore;
using static System.Net.Mime.MediaTypeNames;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Recommendations;
using Microsoft.AspNetCore.Authorization;
using AuroraBricksIntex.Infrastructure;

namespace AuroraBricksIntex.Controllers
{
    public class HomeController : Controller
    {
        private ILegoRepository _repo;

        public HomeController(ILegoRepository temp)
        {
            _repo = temp;
        }


        //pagination info and filtering to categories
        public ViewResult Index(string? colorType, string? productCategoryType, int pageNum = 1, int pageSize = 10)
        {
            // pageSize = Math.Clamp(pageSize, 5, 20);
            pageSize = pageSize;

            var productData = new ProductsListViewModel
            {
                Products = _repo.Products
            .Where(x => x.Category == productCategoryType || productCategoryType == null)
            .Where(x => x.PrimaryColor == colorType || colorType == null)
            .OrderBy(x => x.Name)
            .Skip(pageSize * (pageNum - 1))
            .Take(pageSize),

            //    Colors = _repo.Products
            //.Where(x => x.PrimaryColor == colorType || colorType == null)
            //.OrderBy(x => x.PrimaryColor)
            //.Skip(pageSize * (pageNum - 1))
            //.Take(pageSize),


                PaginationInfo = new PaginationInfo
                {
                    CurrentPage = pageNum,
                    ItemsPerPage = pageSize,
                    TotalItems = productCategoryType == null ? _repo.Products.Count() : _repo.Products.Where(x => x.Category == productCategoryType).Count(),
                    //TotalItems = colorType == null ? _repo.Products.Count() : _repo.Products.Where(x => x.PrimaryColor == colorType).Count(),
                },

                CurrentProductType = productCategoryType,
                //CurrentColorType = colorType
            };

            return View(productData);
        }



        public IActionResult AboutUs()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
        public IActionResult ConfirmProductChange()
        {
            return View();
        }

        public IActionResult ConfirmProductDelete()
        {
            return View();
        }

        // Page to show details of one product
        public IActionResult ProductDetails(int ProductId)
        {
            int recommend = 4; // number of related recommendations to display
            var productDetail = new RelatedProductsViewModel
            {
                Products = _repo.Products
              .Where(x => x.ProductId == ProductId), // can use to find recommendations related to the productID passed
                                                     //.OrderBy(x => x.Name) // can filter by highest value score if wanted
                                                     //.Take(recommend),
                Recommendations = _repo.SimilarProducts
              .Where(x => x.ProductId == ProductId),
            };
            return View(productDetail);
        }


        // CRUD FUNCTIONALITY

        //PRODUCT SECTION

        // Add

        [HttpGet]
        [Authorize]
        //[Authorize(Roles = "Admin")]
        public IActionResult AddProduct()
        {
            ViewBag.Products = _repo.Products  // populates viewbag Products
                .OrderBy(x => x.Name)
                .ToList();

            return View();
        }

        [HttpPost]
        [Authorize]
        //[Authorize(Roles = "Admin")]
        public IActionResult AddProduct(Product response)
        {
            if (ModelState.IsValid)
            {
                _repo.AddProduct(response);
                return View("ConfirmProductChange", response);
            }
            else
            {
                // Handle invalid ModelState
                return View(response); // Return the same view with validation errors
            }
        }

        [Authorize]
        //[Authorize(Roles = "Admin")]
        public IActionResult ProductList()
        {
            // Linq  (sequal language)
            var Products = _repo.Products
                .OrderBy(x => x.Name).ToList();

            return View(Products);
        }


        // Edit 
        [HttpGet]
        [Authorize]
        //[Authorize(Roles = "Admin")]
        public IActionResult EditProduct(int id)
        {
            var recordToEdit = _repo.Products
            .Single(x => x.ProductId == id);

            ViewBag.Products = _repo.Products
                .OrderBy(x => x.Name)
                .ToList();

            return View("EditProduct", recordToEdit);
        }

        [HttpPost]
        [Authorize]
        //[Authorize(Roles = "Admin")]
        public IActionResult EditProduct(Product updateInfo)
        {
            _repo.EditProduct(updateInfo);
  
            return RedirectToAction("ProductList");
        }

        // Delete 
        [HttpGet]
        [Authorize]
        //[Authorize(Roles = "Admin")]
        public IActionResult DeleteProduct(int id)
        {
            var recordToDelete = _repo.Products
                .Single(x => x.ProductId == id);


            return View(recordToDelete);
        }

        // Delete 
        [HttpPost]
        [Authorize]
        //[Authorize(Roles = "Admin")]
        public IActionResult DeleteProduct(Product deleteInfo)
        {
            _repo.DeleteProduct(deleteInfo);

            return RedirectToAction("ProductList");
        }

        //// USER SECTION

        //// Add

        //[HttpGet]
        //public IActionResult AddUser()
        //{
        //    ViewBag.Users = _repo.Users  // populates viewbag Users
        //        .OrderBy(x => x.Name)
        //        .ToList();

        //    return View();
        //}

        //[HttpPost]
        //public IActionResult AddUser(User response)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        _repo.AddUser(response);         // called the same but calling AddUser from repo
        //    }

        //    return View("SuccessUserAdd", response);
        //}


        //public IActionResult UserList()
        //{
        //    // Linq  (sequal language)
        //    var Users = _repo.Users
        //        .OrderBy(x => x.Name).ToList();

        //    return View(Users);
        //}


        //// Edit 
        //[HttpGet]
        //public IActionResult EditUser(int id)
        //{
        //    var recordToEdit = _repo.Users
        //    .Single(x => x.UserId == id);

        //    ViewBag.Users = _repo.Users
        //        .OrderBy(x => x.Name)
        //        .ToList();

        //    return View("AddUser", recordToEdit);
        //}

        //[HttpPost]
        //public IActionResult EditUser(User updateInfo)
        //{
        //    _repo.EditUser(updateInfo);

        //    return RedirectToAction("UserList");
        //}

        //// Delete 
        //[HttpGet]
        //public IActionResult DeleteUser(int id)
        //{
        //    var recordToDelete = _repo.Users
        //        .Single(x => x.UserId == id);


        //    return View(recordToDelete);
        //}

        //// Delete 
        //[HttpPost]
        //public IActionResult DeleteUser(User deleteInfo)
        //{
        //    _repo.DeleteUser(deleteInfo);

        //    return RedirectToAction("UserList");
        //}


        // Order Section


        // Checkout action
        [HttpPost]
        [Authorize]
        public IActionResult Checkout(DateTime dateTime, DateOnly dateOnly, TimeOnly timeOnly)
        {
            // Retrieve cart from session
            var cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();

            // Create a new order
            var order = new Order
            {
                Date = dateOnly,
                Time = timeOnly,
                DayOfWeek = dateTime.DayOfWeek.ToString(),
                EntryMode = "CVC",
                TypeOfTransaction = "Online",
                CountryOfTransaction = "USA",
                ShippingAddress = "USA",
                Bank = "Barclays",
                TypeOfCard = "Visa",
            };

            // Add line items to the order
            foreach (var line in cart.Lines)
            {
                order.LineItems.Add(new LineItem
                {
                    ProductId = line.Product.ProductId,
                    Qty = (byte)line.Quantity,


                    // You may need to adjust other properties based on your requirements
                });
            }

            // Save the order to the database
            _repo.AddOrder(order);

            // Clear the cart after checkout
            cart.Clear();
            HttpContext.Session.SetJson("cart", cart);

            // Redirect to a confirmation page
            return RedirectToAction("ConfirmOrderAdd");
        }

        public IActionResult ConfirmOrderAdd()
        {
            // Retrieve the most recently added order based on timestamp
            Order order = _repo.Orders.OrderByDescending(o => o.TransactionId).FirstOrDefault();

            // Check if the order is not null
            if (order != null)
            {
                return View(order);
            }
            else
            {
                // If no order is found, handle the situation accordingly, such as redirecting to an error page
                return RedirectToAction("Error", "Home"); // Example redirection to the error page
            }
        }
        // This action handles the form submission
        [HttpPost]

AuroraBricksIntex/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "About Us";
}


<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6 d-flex justify-content-center"><img class="card-img-top mb-5 mb-md-0 max-width-img mx-auto" src="~/images/AuroraBricksOutline.png" alt="Auroa Bricks" width="300px" /></div>
            <div class="col-md-6 justify-content-around">
                <h1 class="display-5 fw-bolder">Meet Aurora Brickwell</h1>
                <p class="lead">

                    Aurora Brickwell isn't just another LEGO enthusiast; she's a TikTok-based LEGO influencer with a passion for building and sharing her creations. With her captivating content and infectious enthusiasm, Aurora has amassed a loyal following who eagerly await her next masterpiece.
                </p>
                <h3>From TikTok to Your Doorstep</h3>
                   
                <p class="lead">
                    As Aurora's following grew, so did the demand for her unique LEGO creations. Inspired by the overwhelming support and encouragement from her followers, Aurora decided to take her passion to the next level by launching Aurora Bricks.
                    This website serves as a platform to showcase her creations and make the process of acquiring them easier for her fans.
                </p>
            </div>
        </div>
        <br />
        <h3>Craftsmanship and Creativity.</h3>
        <p class="lead">
            At Aurora Bricks, each creation is meticulously designed and crafted with the utmost attention to detail. From intricate cityscapes to iconic landmarks, Aurora and her team pour their creativity and expertise into every build, ensuring that each piece is truly one-of-a-kind.
        </p>        
        <h3>Gratitude and Appreciation</h3>
        <p class="lead">
            Aurora Brickwell and the entire team at Aurora Bricks are incredibly grateful for the unwavering support and enthusiasm shown by their followers. It's thanks to this community of LEGO lovers that Aurora's passion has blossomed into something truly extraordinary. Every like, comment, and share fuels their creativity and drives them to continue pushing the boundaries of LEGO artistry.
        </p>
        <h3>Join the Aurora Bricks Community</h3>
        <p class="lead">
            Whether you're a seasoned LEGO collector or a newcomer to the world of bricks, Aurora Bricks invites you to join their community of like-minded enthusiasts. Explore their collection of stunning creations, follow along on their journey through social media, and be inspired to unleash your own creativity with LEGO.
            Thank you for being a part of the Aurora Bricks family. Together, let's build something amazing!
        </p>
    </div>
</section>

AuroraBricksIntex/Views/Home/AddProduct.cshtml
@{
    ViewData["Title"] = "Add Product";
}

@model Product

<!DOCTYPE html>
<html>
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f5f5f5;
    }

    .container {
        max-width: 600px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin-bottom: 100px; /* Adjust bottom margin to accommodate privacy banner */
    }

    h1, h2 {
        color: #333;
    }

    form {
        margin-top: 20px;
    }

    label {
        display: block;
        margin-bottom: 5px;
        font-weight: bold;
    }

    input[type="text"],
    input[type="number"],
    select,
    textarea {
        width: 100%;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    select {
        appearance: none;
        -webkit-appearance: none;
        -moz-appearance: none;
        background-image: url('data:image/svg+xml;utf8,<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M7 10l5 5 5-5z"/></svg>');
        background-position: right 8px top 50%;
        background-repeat: no-repeat;
        background-size: 24px;
        padding-right: 40px;
    }

    textarea {
        resize: vertical;
    }

    button[type="submit"] {
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }

    /* Privacy banner styles */
    #cookieConsentBanner {
        position: fixed;
        bottom: 0;
        left: 0;
        width: 100%;
        background-color: #f5f5f5;
        padding: 10px;
        text-align: center;
        box-shadow: 0 -2px 5px rgba(0, 0, 0, 0.1);
    }

        #cookieConsentBanner p {
            margin: 0;
        }

    #acceptCookies,
    #closeBanner {
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        padding: 5px 10px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

        #acceptCookies:hover,
        #closeBanner:hover {
            background-color: #0056b3;
        }
</style>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BuildWithAuroraBricks</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AuroraBricksIntex.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <h1>Add New Product</h1>

        <form method="post">
            <div class="form-group">
                <label asp-for="Name">Product Name</label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Year">Year</label>
                <input asp-for="Year" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="NumParts">Number of Parts</label>
                <input asp-for="NumParts" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Price">Price</label>
                <input asp-for="Price" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="ImgLink">Image Link</label>
                <input asp-for="ImgLink" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description">Description</label>
                <input asp-for="Description" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="PrimaryColor">Primary Color</label>
                <select asp-for="PrimaryColor" class="form-control">
                    <option value="">Primary Color</option>
                    <option value="Black">Black</option>
                    <option value="Blue">Blue</option>
                    <option value="Brown">Brown</option>
                    <option value="Green">Green</option>
                    <option value="Grey">Grey</option>
                    <option value="Orange">Orange</option>
                    <option value="Red">Red</option>
                    <option value="Tan">Tan</option>
                    <option value="White">White</option>
                    <option value="Yellow">Yellow</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryColor">Secondary Color</label>
                <select asp-for="SecondaryColor" class="form-control">
                    <option value="">Secondary Color</option>
                    <option value="Black">Black</option>
                    <option value="Blue">Blue</option>
                    <option value="Brown">Brown</option>
                    <option value="Green">Green</option>
                    <option value="Grey">Grey</option>
                    <option value="Orange">Orange</option>
                    <option value="Red">Red</option>
                    <option value="Tan">Tan</option>
                    <option value="White">White</option>
                    <option value="Yellow">Yellow</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Category">Category</label>
                <select asp-for="Category" class="form-control">
                    <option value="">Category</option>
                    <option value="Animal">Animal</option>
                    <option value="Harry Potter">Harry Potter</option>
                    <option value="Minifig">Mini Figure</option>
                    <option value="Misc">Miscellaneous</option>
                    <option value="Part">Part</option>
                    <option value="Star Wars">Star Wars</option>
                    <option value="Structure">Structure</option>
                    <option value="Vehicle">Vehicle</option>
                </select>
                <br/>
            </div>
            <button class="btn btn-info" type="submit">Add Product</button>
        </form>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

AuroraBricksIntex/Views/Home/CheckoutPage.cshtml
@model AuroraBricksIntex.Models.Order

<!DOCTYPE html>
<html>
<head>
    <title>Confirmation Page</title>
</head>
<body>
    <h2>Confirmation Page</h2>

    <form method="post">
        <div>
            <label for="date">Date:</label>
            <input type="date" id="date" name="date" value="@DateTime.Now.ToString("yyyy-MM-dd")" readonly />
        </div>
        <div>
            <label for="dayOfWeek">Day of Week:</label>
            <input type="text" id="dayOfWeek" name="dayOfWeek" value="@DateTime.Now.DayOfWeek.ToString()" readonly />
        </div>
        <div>
            <label for="time">Time:</label>
            <input type="time" id="time" name="time" value="@DateTime.Now.ToString("HH:mm")" readonly />
        </div>
        <div>
            <label for="entryMode">Entry Mode:</label>
            <select id="entryMode" name="entryMode">
                <option value="Tap">Tap</option>
                <option value="PIN">PIN</option>
                <option value="CVC">CVC</option>
            </select>
        </div>
        <div>
            <label for="amount">Amount:</label>
            <input type="number" id="amount" name="amount" />
        </div>
        <div>
            <label for="typeOfTransaction">Type of Transaction:</label>
            <input type="text" id="typeOfTransaction" name="typeOfTransaction" value="Online" readonly />
        </div>
        <div>
            <label for="countryOfTransaction">Country of Transaction:</label>
            <select id="countryOfTransaction" name="countryOfTransaction">
                <option value="UK">UK</option>
                <option value="USA">USA</option>
                <option value="India">India</option>
                <option value="China">China</option>
                <option value="Russia">Russia</option>
            </select>
        </div>
        <div>
            <label for="shippingAddress">Shipping Address:</label>
            <textarea id="shippingAddress" name="shippingAddress"></textarea>
        </div>
        <div>
            <label for="bank">Bank:</label>
            <select id="bank" name="bank">
                <option value="Barclays">Barclays</option>
                <option value="HSBC">HSBC</option>
                <option value="Metro">Metro</option>
            </select>
        </div>
        <div>
            <label for="typeOfCard">Type of Card:</label>
            <select id="typeOfCard" name="typeOfCard">
                <option value="Visa">Visa</option>
                <option value="MasterCard">MasterCard</option>
            </select>
        </div>
        <button type="submit">Submit</button>
    </form>

</body>
</html>

AuroraBricksIntex/Views/Home/ConfirmProductChange.cshtml
@{
    ViewData["Title"] = "Product Updates";
}

@model Product

<h1>@Model.Name has been successfully added/updated in the database.</h1>
<a class="btn btn-light" asp-controller="Home" asp-action="ProductList">View Products</a>

AuroraBricksIntex/Views/Home/ConfirmProductDelete.cshtml
@{
    ViewData["Title"] = "Delete Product Confirmation";
}

@model Product

<h1>@Model.Name has been successfully deleted from the database.</h1>
<a class="btn btn-light" asp-controller="Home" asp-action="ProductList">View Products</a>

AuroraBricksIntex/Views/Home/DeleteProduct.cshtml
@{
    ViewData["Title"] = "Delete Product";
}

@model Product

<h2>Confirm Deletion of @Model.Name?</h2>

<form method="post">
    <input type="hidden" asp-for="ProductId" />

    <button class="btn btn-danger" type="submit">Delete</button>
    <a class="btn btn-info" asp-controller="Home" asp-action="ProductList">Cancel</a>
</form>

AuroraBricksIntex/Views/Home/EditProduct.cshtml
@{
    ViewData["Title"] = "Edit Product";
}

@model Product

<h1>Edit Product</h1>

<form method="post">
    <input type="hidden" asp-for="ProductId" />

    <label asp-for="Name">Product Name</label>
    <input asp-for="Name" />
    <br />
    <label asp-for="Year">Year</label>
    <input asp-for="Year" />
    <br />
    <label asp-for="NumParts">Number of Parts</label>
    <input asp-for="NumParts" />
    <br />
    <label asp-for="Price">Price</label>
    <input asp-for="Price" />
    <br />
    <label asp-for="ImgLink">Image Link</label>
    <input asp-for="ImgLink" />
    <br />
    <label asp-for="Description">Description</label>
    <input asp-for="Description" />
    <br />
    <select asp-for="PrimaryColor">
        <option value="">Primary Color</option>
        <option value="Black">Black</option>
        <option value="Blue">Blue</option>
        <option value="Brown">Brown</option>
        <option value="Green">Green</option>
        <option value="Grey">Grey</option>
        <option value="Orange">Orange</option>
        <option value="Red">Red</option>
        <option value="Tan">Tan</option>
        <option value="White">White</option>
        <option value="Yellow">Yellow</option>
    </select>
    <br />
    <select asp-for="SecondaryColor">
        <option value="">Secondary Color</option>
        <option value="Black">Black</option>
        <option value="Blue">Blue</option>
        <option value="Brown">Brown</option>
        <option value="Green">Green</option>
        <option value="Grey">Grey</option>
        <option value="Orange">Orange</option>
        <option value="Red">Red</option>
        <option value="Tan">Tan</option>
        <option value="White">White</option>
        <option value="Yellow">Yellow</option>
    </select>
    <br />
    <select asp-for="Category">
        <option value="">Category</option>
        <option value="Animal">Animal</option>
        <option value="Harry Potter">Harry Potter</option>
        <option value="Minifig">Mini Figure</option>
        <option value="Misc">Miscellaneous</option>
        <option value="Part">Part</option>
        <option value="Star Wars">Star Wars</option>
        <option value="Structure">Structure</option>
        <option value="Vehicle">Vehicle</option>

        @*         @foreach (Product.Category c in ViewBag.Products)
        {
        <option value="@c.Category">@c.Category</option>
        } *@
    </select>
    <br />
    <button class="btn btn-info" type="submit">Edit Product</button>

</form>

AuroraBricksIntex/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model ProductsListViewModel



<div class="row m-1 p-1">
    <!--Filter By Category-->
    <div class="col-4">
        <vc:product-category-types />
    </div>
    <!--Filter By Color-->     
    <div class="col-3">
         <vc:color-types />
    </div>
       
    <!--NEEDS TO BE BUILT IN ANOTHER COMPONENT PAGE-->

    <div class="col-4">
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="paginationDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                Items per page
            </button>
            <ul class="dropdown-menu" aria-labelledby="categoryDropdown">
                <li>
                    <a class="btn dropdown-item @(null == ViewBag.SelectedProductType? "btn-primary" : "btn-outline-secondary" )" asp-controller="Home" asp-action="Index" asp-route-productCategoryType="" asp-route-pageNum="" asp-route-pageSize="5">5 Items</a>
                </li>
                <li>
                    <a class="btn dropdown-item @(null == ViewBag.SelectedProductType? "btn-primary" : "btn-outline-secondary" )" asp-controller="Home" asp-action="Index" asp-route-productCategoryType="" asp-route-pageNum="" asp-route-pageSize="10">10 Items</a>
                </li>
                <li>
                    <a class="btn dropdown-item @(null == ViewBag.SelectedProductType? "btn-primary" : "btn-outline-secondary" )" asp-controller="Home" asp-action="Index" asp-route-productCategoryType="" asp-route-pageNum="" asp-route-pageSize="20">20 Items</a>
                </li>
            </ul>
        </div>
    </div>


</div>
<!-- Product Recommendation Section-->

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <h2 class="fw-bolder mb-4">Recommended for you</h2>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                @foreach (Product p in Model.Products)
            {
                <partial name="ProductSummary" model="p" />

            }
        </div>
    </div>
</section>


<!--Pagination Section-->
<div page-model="@Model.PaginationInfo" page-action="Index" page-classes-enabled="true" page-class="btn"
     page-class-normal="btn-outline-dark" page-class-selected="btn-info" page-url-productType="@Model.CurrentProductType" class="btn-group pull-right m-1"></div>


<!--Cookie Code-->
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function () {
        // Check if the user has already accepted cookies
        if (!localStorage.getItem('cookiesAccepted')) {
            var banner = document.getElementById('cookieConsentBanner');
            banner.style.display = 'flex'; // Show the banner
        }

        // When the user clicks on 'Accept & Shop', hide the banner and set local storage
        document.getElementById('acceptCookies').addEventListener('click', function () {
            document.getElementById('cookieConsentBanner').style.display = 'none';
            localStorage.setItem('cookiesAccepted', 'true'); // Set the flag in local storage
            // Here, you would also handle the cookie acceptance, such as setting a cookie
        });

        // When the user clicks the '×' button, hide the banner
        document.getElementById('closeBanner').addEventListener('click', function () {
            document.getElementById('cookieConsentBanner').style.display = 'none';
        });
    });
</script>


<!-- Cookie Consent Banner with linked privacy policy -->
<div id="cookieConsentBanner" class="cookie-consent-banner">
    <p>We use technologies such as cookies to enable the best shopping experience for you, as well as for analytics, personalization, dynamic content and for marketing purposes. <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>.</p>
    <button id="acceptCookies" class="accept-cookies">Accept & Shop</button>
    <button id="closeBanner" class="close-banner">&times;</button>
</div>